package com.wisekrakr.firstgame.engine;

public enum GameObjectVisualizationType {
    SPACESHIP,
    ASTEROID,
    DEBRIS,
    ROTUNDA,
    EXHAUST,
    BULLET,
    LASER_BEAM,
    SPACE_MINE,
    ENEMY_CHASER,
    BLINKER,
    EWM,
    MUTATOR,
    PEST,
    DODGER,
    HOMER,
    MOTHERSHIP,
    SHITTER,
    SHOTTY,
    FACE_HUGGER,
    MISSILE,
    SPORE,
    MINION,
    POWERUP_MISSILE,
    POWERUP_SHIELD,
    POWERUP_MINION,
    POWERUP_HEALTH,
    SHIELD,
    POWERUP_GENERATOR,
    TEST_QUEST,
    TEST_NPC,
    MISSION_END
}
