package com.wisekrakr.firstgame.engine;

public enum GameObjectType {
    SPACESHIP,
    ENEMY,
    ASTEROID,
    DEBRIS,
    ROTUNDA,
    EXHAUST,
    BULLET,
    LASER_BEAM,
    SPACE_MINE,
    ENEMY_CHASER,
    BLINKER,
    GANG,
    ELS,
    MUTATOR,
    PEST,
    DODGER,
    HOMER,
    MOTHERSHIP,
    SHITTER,
    SHOTTY,
    FACE_HUGGER,
    PLANET,
    MISSILE,
    SPORE,
    MINION_SHOOTER,
    MINION_FIGHTER,
    POWERUP_MISSILE,
    POWERUP_SHIELD,
    POWERUP_MINION,
    POWERUP_HEALTH,
    SHIELD,
    POWERUP_GENERATOR

}
